# Flow in all environments (pull the metadata from Salesforce into Git).
# This workflow consists of two jobs:
# - The first runs `orgflow env:list` and transforms the output into a matrix for GitHub actions.
# - The second uses the matrix created in the first step to tun `orgflow env:flowin` for all the environments.

name: Flow in all environments
on:
  schedule:
    - cron:  '0 1 * * *' # Runs nightly at 1am.
  workflow_dispatch: # Can also be manually triggered, if needed.

jobs:
  create-matrix:
    name: "Get Environments"
    runs-on: ubuntu-latest    
    container: 
      image: orgflow/cli:latest
      env:
        ORGFLOW_ACCEPTEULA: true # If someone has a license key then they've already accepted the EULA.
        ORGFLOW_STACKNAME: ${{ secrets.ORGFLOW_STACKNAME }}      
        ORGFLOW_LICENSEKEY: ${{ secrets.ORGFLOW_LICENSEKEY }}
        ORGFLOW_OUTPUTTEMPLATE_WARNING: "::warning  title=OrgFlow Warning::$$msg$$"
        ORGFLOW_OUTPUTTEMPLATE_ERROR: "::error title=OrgFlow Error::$$msg$$"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    # Use jq to transform the output from env:list into the format expected for a matrix strategy:
    - id: set-matrix
      run: echo "::set-output name=matrix::`orgflow env:list --output=json | jq '[.[] | .name]' -c`"
      
  flow-in:
    name: "Flow In Environment"
    needs: create-matrix
    runs-on: ubuntu-latest    
    container: 
      image: orgflow/cli
      env:
        ORGFLOW_ACCEPTEULA: true # If someone has a license key then they've already accepted the EULA.
        ORGFLOW_STACKNAME: ${{ secrets.ORGFLOW_STACKNAME }}      
        ORGFLOW_LICENSEKEY: ${{ secrets.ORGFLOW_LICENSEKEY }}   
        SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
        SALESFORCE_PASSWORD: ${{ secrets.SALESFORCE_PASSWORD }} 
        ORGFLOW_OUTPUTTEMPLATE_WARNING: "::warning  title=OrgFlow Warning::$$msg$$"
        ORGFLOW_OUTPUTTEMPLATE_ERROR: "::error title=OrgFlow Error::$$msg$$"
    strategy:
      fail-fast: false # If one environment fails, don't allow GitHub to cancel the jobs for all the rest. 
      matrix: 
        environmentName: ${{fromJson(needs.create-matrix.outputs.matrix)}}
          
    steps:
      # Verify input:
      - name: Verify input
        id: verifyInput
        run: |
          if ["$ORGFLOW_STACKNAME" == ""]; then echo "::error tile=Missing input value::Repository secret ORGFLOW_STACKNAME has not been set. See the readme for more details." && exit 1; fi;
          if ["$ORGFLOW_LICENSEKEY" == ""]; then echo "::error tile=Missing input value::Repository secret ORGFLOW_LICENSEKEY has not been set. See the readme for more details." && exit 1; fi;
          if ["$SALESFORCE_USERNAME" == ""]; then echo "::error tile=Missing input value::Repository secret SALESFORCE_USERNAME has not been set. See the readme for more details." && exit 1; fi;
          if ["$SALESFORCE_PASSWORD" == ""]; then echo "::error tile=Missing input value::Repository secret SALESFORCE_PASSWORD has not been set. See the readme for more details." && exit 1; fi;
          
      # Configure Git:
      - uses: orgflow-actions/configure-git@v2
        with:
          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}

      # Configure auth:
      - uses: orgflow-actions/set-salesforce-auth@v1
        id: set-salesforce-auth
        with:
          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
          username: ${{ secrets.SALESFORCE_USERNAME }}
          password: ${{ secrets.SALESFORCE_PASSWORD }}
          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}       
          
      # Run OrgFlow command:
      - name: env:flowin
        run: |
          orgflow env:flowin -e="${{ matrix.environmentName }}"
        env:
          ORGFLOW_ENCRYPTIONKEY: ${{ steps.set-salesforce-auth.outputs.encryption-key }}
      
      # Publish diagnostic bundles to artifacts (if any):
      - name: Publish diagnostic bundle as artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Diagnostic Bundles
          path: |
            /tmp/OrgFlow_Diagnostics_*.zip
          retention-days: 3
          if-no-files-found: ignore
