# Flow in an environment (sync metadata from Salesforce into Git)

name: Commit metadata changes from org

on:
  # This workflow is always manually executed.
  workflow_dispatch:
    inputs:
      environmentName:
        description: "Name of environment to flow in:"
        required: true
      commitMessage:
        description: "Commit message (leave empty to use a default message):"
        required: false

jobs:
  flow-in:
    name: Flow environment in
    runs-on: ubuntu-latest

    steps:
      # Verify secrets:
      - name: Verify secrets
        run: |
          if ["${{ secrets.ORGFLOW_STACKNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_STACKNAME has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.ORGFLOW_LICENSEKEY }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_LICENSEKEY has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.SALESFORCE_USERNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_USERNAME has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.SALESFORCE_PASSWORD }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_PASSWORD has not been set. See the Readme for more details." && exit 1; fi;

      # Install and configure OrgFlow:
      - name: Install OrgFlow
        uses: orgflow-actions/setup@v1
        with:
          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
          salesforce-username: ${{ secrets.SALESFORCE_USERNAME }}
          salesforce-password: ${{ secrets.SALESFORCE_PASSWORD }}
          git-username: ${{ github.actor }}
          git-password: ${{ secrets.GITHUB_TOKEN }}
          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
        env:
          ORGFLOW_ACCEPTEULA: "true"

      # Run OrgFlow command to flow in environment:
      - name: Run env:flowin
        run: |
          orgflow env:flowin --environment="${{ github.event.inputs.environmentName }}" --message="${{ github.event.inputs.commitMessage }} --waitForLock=5"
