# Add a new environment to this repo's stack

name: Create an environment

on:
  # This workflow is always manually executed.
  workflow_dispatch:
    inputs:
      environmentName:
        description: "Name of environment to create:"
        required: true
      sandboxName:
        description: "Name of environment's sandbox:"
        required: true
      branchName:
        description: "Name of environment's Git branch:"
        required: true

# This action uses GitHub's built in token authentication for Git repositories.  
# Read more at https://docs.github.com/en/actions/security-guides/automatic-token-authentication.
permissions:
  # Ensure that OrgFlow can push the new branch back to the remote repository:
  contents: write

jobs:
  env-create:
    name: Create environment
    runs-on: ubuntu-latest

    steps:
      # Verify secrets:
      - name: Verify secrets
        run: |
          if ["${{ secrets.ORGFLOW_STACKNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_STACKNAME has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.ORGFLOW_LICENSEKEY }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_LICENSEKEY has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.SALESFORCE_USERNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_USERNAME has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.SALESFORCE_PASSWORD }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_PASSWORD has not been set. See the Readme for more details." && exit 1; fi;

      # Install and configure OrgFlow:
      - name: Install OrgFlow
        uses: orgflow-actions/setup@v1
        with:
          version: 2
          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
          salesforce-username: ${{ secrets.SALESFORCE_USERNAME }}
          salesforce-password: ${{ secrets.SALESFORCE_PASSWORD }}
          git-username: ${{ github.actor }}
          git-password: ${{ secrets.GITHUB_TOKEN }}
          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
        env:
          ORGFLOW__ACCEPTEULA: "true"

      # Run OrgFlow command to create environment:
      - name: Run env:create
        run: |
          orgflow env:create --environment="${{ github.event.inputs.environmentName }}" --sandboxName="${{ github.event.inputs.sandboxName }}" --branchName="${{ github.event.inputs.branchName }}" --useExistingSandbox --useExistingBranch --noConfirm --waitForLock=5

      # Tag this environment so that the upstream merge workflow can filter based on this tag:
      - name: Run env:tags:set
        run: |
          orgflow env:tags:set --environment="${{ github.event.inputs.environmentName }}" --tags="upstreamMergeTarget"
