# Flow out an environment (sync metadata from Git to Salesforce)

name: Deploy metadata

on:
  # This workflow is always manually executed.
  workflow_dispatch:
    inputs:
      environmentName:
        description: "Name of environment to flow out:"
        required: true

jobs:
  flow-out:
    name: Flow environment out
    runs-on: ubuntu-latest

    steps:
      # Verify secrets:
      - name: Verify secrets
        run: |
          if ["${{ secrets.ORGFLOW_STACKNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_STACKNAME has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.ORGFLOW_LICENSEKEY }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_LICENSEKEY has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.SALESFORCE_USERNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_USERNAME has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.SALESFORCE_PASSWORD }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_PASSWORD has not been set. See the Readme for more details." && exit 1; fi;

      # Install and configure OrgFlow:
      - name: Install OrgFlow
        uses: orgflow-actions/setup@v1
        with:
          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
          salesforce-username: ${{ secrets.SALESFORCE_USERNAME }}
          salesforce-password: ${{ secrets.SALESFORCE_PASSWORD }}
          git-username: ${{ github.actor }}
          git-password: ${{ secrets.GITHUB_TOKEN }}
          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
        env:
          ORGFLOW_ACCEPTEULA: "true"

      # Run OrgFlow command to flow in environment:
      # It's good practice to flow in before you flow out, to avoid loss of data in the Salesforce org:
      - name: Run env:flowin
        run: |
          orgflow env:flowin --environment="${{ github.event.inputs.environmentName }}" --waitForLock=5

      # Run OrgFlow command to flow out environment:
      # Flow out to deploy the changes from Git to Salesforce:
      - name: Run env:flowout
        run: |
          orgflow env:flowout --environment="${{ github.event.inputs.environmentName }}" --waitForLock=5
