# Creates a new OrgFlow stack for the current repo. In OrgFlow, a stack is a collection of environments, and maps to a single git repo. Your stack will get linked to this repo, and any environments that you create will be backed by branches within this repo.
# NOTE: for simplicity, we assume some input- we'll name your production environment 'Production', and we'll commit all its metadata to a branch called 'main'.
name: Create the stack

on:
  # This action is always manually executed.
  workflow_dispatch:

# The stack:create command needs to be able to push changes back to the repo.
permissions:
  contents: write  

jobs:
  stack-create:
    name: Create Stack
    runs-on: ubuntu-latest    
    container: 
      image: orgflow/cli-private:latest
      credentials:
          username: paynecrl97
          password: ${{  secrets.DOCKERHUB_PASSWORD }}
    env:
      ORGFLOW_ACCEPTEULA: true # If someone has a license key then they've already accepted the EULA.    
      ORGFLOW_LICENSEKEY: ${{ secrets.ORGFLOW_LICENSEKEY }}
      ORGFLOW_STACKNAME: ${{ secrets.ORGFLOW_STACKNAME }}
      SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
      SALESFORCE_PASSWORD: ${{ secrets.SALESFORCE_PASSWORD }}
      
    steps:
      # Verify input:
      - name: Verify stack name
        id: verifyStackName
        if: ${{always() && env.ORGFLOW_STACKNAME == '' }}
        run: |
          echo 'Repository secret ORGFLOW_STACKNAME has not been set. See the readme for more details.
          exit 1
      - name: Verify license key
        id: verifyLicenseKey
        if: ${{always() && env.ORGFLOW_LICENSEKEY == '' }}
        run: |
          echo 'Repository secret ORGFLOW_LICENSEKEY has not been set. See the readme for more details.
          exit 1
      - name: Verify Salesforce username
        id: verifySalesforceUsername
        if: ${{always() && env.SALESFORCE_USERNAME == '' }}
        run: |
          echo 'Repository secret SALESFORCE_USERNAME has not been set. See the readme for more details.'
          exit 1
      - name: Verify Salesforce password
        id: verifySalesforcePassword
        if: ${{always() && env.SALESFORCE_PASSWORD == '' }}
        run: |
          echo 'Repository secret SALESFORCE_PASSWORD has not been set. See the readme for more details.'
          exit 1
      
      # Configure Git:
      - uses: orgflow-actions/configure-git@v2.0.0
        with:
          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
          
      # Run OrgFlow command:
      - name: stack:create
        run: |
          orgflow stack:create -n="${{ secrets.ORGFLOW_STACKNAME }}" -r="$GITHUB_SERVER_URL/${{ github.repository }}.git" -b=production -u="${{ secrets.SALESFORCE_USERNAME }}" -p="${{ secrets.SALESFORCE_PASSWORD }}" -e=Production      
      
      # Publish diagnostic bundles to artifacts (if any):
      - name: Publish diagnostic bundle as artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Diagnostic Bundles
          path: |
            /tmp/OrgFlow_Diagnostics_*.zip
          retention-days: 3
          if-no-files-found: ignore
