# Delete the stack and all of its environments and their current state.

name: Delete the stack

on:
  # This action must be manually executed
  workflow_dispatch:
    inputs:
      confirmation:
        description: > 
          Are you sure?
          
          This action is destructive and irrevocable. Type 'yes' to continue.

          Your Git repository, branches, and sandboxes will remain intact.
        required: true

jobs:
  stack-delete:
    name: Delete Stack
    runs-on: ubuntu-latest    
    container: 
      image: orgflow/cli:latest
    env:
      ORGFLOW_ACCEPTEULA: true # If someone has a license key then they've already accepted the EULA.
      ORGFLOW_STACKNAME: ${{ secrets.ORGFLOW_STACKNAME }}      
      ORGFLOW_LICENSEKEY: ${{ secrets.ORGFLOW_LICENSEKEY }}

    steps:
      # Verify input:
      - name: Verify stack name
        id: verifyStackName
        if: ${{ always() && env.ORGFLOW_STACKNAME == '' }}
        run: |
          echo 'Repository secret ORGFLOW_STACKNAME has not been set. See the readme for more details.'
          #exit 1
      - name: Verify license key
        id: verifyLicenseKey
        if: ${{ always() && env.ORGFLOW_LICENSEKEY == '' }}
        run: |
          echo 'Repository secret ORGFLOW_LICENSEKEY has not been set. See the readme for more details.'
          exit 

      # Verify that this action has been confirmed:
      - name: Check confirmation
        if: ${{ github.event.inputs.confirmation != 'yes' }}
        run: |
          echo "Please confirm deletion by typing 'yes' at the prompt"
          return 1
      
      # Run OrgFlow command:
      - name: stack:delete
        run: orgflow stack:delete --noConfirm      
      
      # Publish diagnostic bundles to artifacts (if any):
      - name: Publish diagnostic bundle as artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Diagnostic Bundles
          path: |
            /tmp/OrgFlow_Diagnostics_*.zip
          retention-days: 3
          if-no-files-found: ignore
