# Unlock an environment (in case it's left locked).
# OrgFlow locks environments while it is operating on them.
# If an OrgFlow command is abruptly terminated then the lock can fail to be released.
# This workflow allows you to manually unlock an environment in case you have a need to do so.

name: Unlock an environment

on:
  # This workflow is always manually executed.
  workflow_dispatch:
    inputs:
      environmentName:
        description: "Name of environment to unlock:"
        required: true

jobs:
  env-unlock:
    name: Unlock environment
    runs-on: ubuntu-latest

    steps:
      # Verify secrets:
      - name: Verify secrets
        run: |
          if ["${{ secrets.ORGFLOW_STACKNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_STACKNAME has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.ORGFLOW_LICENSEKEY }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_LICENSEKEY has not been set. See the Readme for more details." && exit 1; fi;

      # Install and configure OrgFlow:
      - name: Install OrgFlow
        uses: orgflow-actions/setup@v1
        with:
          version: 3
          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
        env:
          ORGFLOW__ACCEPTEULA: "true"

      # Run OrgFlow command to unlock environment:
      - name: env:unlock
        run: orgflow env:unlock --environment="${{ github.event.inputs.environmentName }}"
