# Validate merge and deployment of a pull request

name: Validate a pull request

on:
  # This workflow runs whenever a pull request is created or updated:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  env-merge:
    name: Run a check-only deployment on the result of the merge
    runs-on: ubuntu-latest

    steps:
      # Verify secrets:
      - name: Verify secrets
        run: |
          if ["${{ secrets.ORGFLOW_STACKNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_STACKNAME has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.ORGFLOW_LICENSEKEY }}" == ""]; then echo "::error title=Missing input value::Repository secret ORGFLOW_LICENSEKEY has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.SALESFORCE_USERNAME }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_USERNAME has not been set. See the Readme for more details." && exit 1; fi;
          if ["${{ secrets.SALESFORCE_PASSWORD }}" == ""]; then echo "::error title=Missing input value::Repository secret SALESFORCE_PASSWORD has not been set. See the Readme for more details." && exit 1; fi;

      # Check out the merge result of the PR
      - name: Check out merge result
        uses: actions/checkout@v3
        with:
          ref: ${{ github.merge_commit_sha }}
          path: merge_result

      # Install and configure OrgFlow:
      - name: Install OrgFlow
        uses: orgflow-actions/setup@v1
        with:
          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
          salesforce-username: ${{ secrets.SALESFORCE_USERNAME }}
          salesforce-password: ${{ secrets.SALESFORCE_PASSWORD }}
          git-username: ${{ github.actor }}
          git-password: ${{ secrets.GITHUB_TOKEN }}
          stack-name: ${{ secrets.ORGFLOW_STACKNAME }}
        env:
          ORGFLOW_ACCEPTEULA: "true"

      # Find the environment that the target branch belongs to:
      - name: Find target environment
        id: find-target-environment
        run: |
          set -e
          output=`orgflow env:list --output=json | jq '[.[] | select(.git.branch == "${{ github.base_ref }}") | .name] | select(. | length > 0)[0]' -r` 
          echo "::set-output name=environment-name::$output";

      # Print a message if target branch does not correspond to an environment.
      # End with success to still allow PRs unrelated to OrgFlow to be merged.
      - name: End with success if target branch does not correspond to an environment
        if: steps.find-target-environment.outputs.environment-name == ''
        run: echo "Target branch '${{ github.base_ref }}' does not correspond to an OrgFlow environment."

      # Run OrgFlow command to do a check-only (validation) outbound flow of merge result to target:
      - name: Run env:flowout
        if: steps.find-target-environment.outputs.environment-name != ''
        id: env-flowout
        run: |
          json=$(orgflow env:flowout --environment=${{ steps.find-target-environment.outputs.environment-name }} --useLocalRepo=$GITHUB_WORKSPACE/merge_result --checkOnly --output=json --waitForLock=5)
          echo "::set-output name=flow-out::$(echo $json | jq '. | del(.retrieve) | del(.result.attempts)' -c)"

      # Post result as a comment on this PR:
      - uses: orgflow-actions/result-to-comment@v1
        if: steps.env-flowout.outputs.flow-out != ''
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          result: ${{ steps.env-flowout.outputs.flow-out }}
          template-path: env-flow-out.liquid