//
//This class contains constants for all possible recurrence types of SF-event.
//
//Author: Gennadiy Pervukhin (11-11-2014)
public class DC_EventRecurrenceType
{
	//
	//Constants
	//
	public static final String DAILY = 'RecursDaily';
	public static final String EVERY_WEEKDAY = 'RecursEveryWeekday';
	
	public static final String WEEKLY = 'RecursWeekly';
	
	public static final String MONTHLY = 'RecursMonthly';
	public static final String MONTHLY_Nth = 'RecursMonthlyNth';
	
	public static final String YEARLY = 'RecursYearly';
	public static final String YEARLY_Nth = 'RecursYearlyNth';
	//
}