//
//This class contains constants for all months in SF.
//
//Author: Gennadiy Pervukhin (11-11-2014)
public class DC_SfMonth
{
	//
	//Constants
	//
	public static final String JANUARY = 'January';
	public static final String FEBRUARY = 'February';
	public static final String MARCH = 'March';
	public static final String APRIL = 'April';
	public static final String MAY = 'May';
	public static final String JUNE = 'June';
	public static final String JULY = 'July';
	public static final String AUGUST = 'August';
	public static final String SEPTEMBER = 'September';
	public static final String OCTOBER = 'October';
	public static final String NOVEMBER = 'November';
	public static final String DECEMBER = 'December';
	//
}