public class OpportunityXsbu  {
 	 public Id RecordTypeId {
          get { return RecordTypeId; }
          set { RecordTypeId = value; }
     }
    public String Xsbu_Account_address {
          get { return Xsbu_Account_address; }
          set { Xsbu_Account_address = value; }
     }
  	 public String Primary_Contact_s_Name {
          get { return Primary_Contact_s_Name; }
          set { Primary_Contact_s_Name = value; }
     }
  	 public String Primary_Contact_s_Email_Address {
          get { return Primary_Contact_s_Email_Address; }
          set { Primary_Contact_s_Email_Address = value; }
     }
  	 public String Primary_Contact_s_Mobile {
          get { return Primary_Contact_s_Mobile; }
          set { Primary_Contact_s_Mobile = value; }
     }
 	 public String Primary_Contact_s_Phone {
          get { return Primary_Contact_s_Phone; }
          set { Primary_Contact_s_Phone = value; }
     }
 	 public String Product_Line_Interested_In {
          get { return Product_Line_Interested_In; }
          set { Product_Line_Interested_In = value; }
     }
 	 public String Xsbu_Prospect_Sender {
          get { return Xsbu_Prospect_Sender; }
          set { Xsbu_Prospect_Sender = value; }
     }
/*  	 public String Q_A {
          get { return Q_A; }
          set { Q_A = value; }
     }
*/
 	 public String Xsbu_Customer_name {
          get { return Xsbu_Customer_name; }
          set { Xsbu_Customer_name = value; }
     }
/*	 public String S2S_Product_Line_Interested_In {
          get { return S2S_Product_Line_Interested_In; }
          set { S2S_Product_Line_Interested_In = value; }
     }
*/
	 public String Source_opp_ID {
          get { return Source_opp_ID; }
          set { Source_opp_ID = value; }
     }
	public String User_Country {
          get { return User_Country; }
          set { User_Country = value; }
     }
/*	public String xsbu_Dealer_s_Sales_Rep {
          get { return xsbu_Dealer_s_Sales_Rep; }
          set { xsbu_Dealer_s_Sales_Rep = value; }
     } */
/*	public String xsbu_dealer_name {
          get { return xsbu_dealer_name; }
          set { xsbu_dealer_name = value; }
     } */
	 public String Name {
          get { return Name; }
          set { Name = value; }
     }
/*     public String CurrencyIsoCode {
          get { return CurrencyIsoCode; }
          set { CurrencyIsoCode = value; }
     }
*/
     public String Description {
          get { return Description; }
          set { Description = value; }
     }
     public String Lost_Opportunity_Reason {
          get { return Lost_Opportunity_Reason; }
          set { Lost_Opportunity_Reason = value; }
     }
     public Decimal Amount {
          get { return Amount; }
          set { Amount = value; }
     }
     public String StageName {
          get { return StageName; }
          set { StageName = value; }
     }
     public String Sub_Stage {
          get { return Sub_Stage; }
          set { Sub_Stage = value; }
     }
     public Datetime CloseDate {
          get { return CloseDate; }
          set { CloseDate = value; }
     }
}