public class QAXsbu {
/*    public String Account_Name {
          get { return Account_Name; }
          set { Account_Name = value; }
     } */
    public String Answer {
          get { return Answer; }
          set { Answer = value; }
     }
    public String Name {
          get { return Name; }
          set { Name = value; }
     }
    public String Question {
          get { return Question; }
          set { Question = value; }
     }
/*    public String Questionnaire_Setup {
          get { return Questionnaire_Setup; }
          set { Questionnaire_Setup = value; }
     } */
    // Our Opportunity Id
    public String Source_Id {
          get { return Source_Id; }
          set { Source_Id = value; }
     }
    // Their Opportunity Id
    public String Opportunity_Name {
          get { return Opportunity_Name; }
          set { Opportunity_Name = value; }
     }
}