// This should be an enum, but that causes issues with select lists
public class RecurrenceTypes 
{ 
    public final string None = 'None';
    public final string Daily = 'Daily';
    public final string DailyEveryWeekday = 'DailyEveryWeekday';
    public final string Weekly = 'Weekly';
    public final string Monthly = 'Monthly';
    public final string MonthlyFixedDate = 'MonthlyFixedDate';
    public final string Yearly = 'Yearly';
    public final string YearlyFixedDate = 'YearlyFixedDate';
}